# Generated by Django 5.1.1 on 2024-09-10 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_address_zip'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='membership',
            field=models.CharField(choices=[('G', 'Bronze'), ('S', 'Solver'), ('G', 'Gold')], default='B', max_length=1),
        ),
    ]
